inicial: q0
estados: ['q0', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10']
finais: ['q1', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10']
transicoes:
  #NÚMEROS
  - origem: q0
    destino: q1
    simbolos: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  - origem: q1
    destino: q1
    simbolos: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  - origem: q1
    destino: q2
    simbolos: ['.']
  - origem: q2
    destino: q3
    simbolos: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  - origem: q3
    destino: q3
    simbolos: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  #PARÊNTESES
  - origem: q0
    destino: q4
    simbolos: ['(', ')']
  #COLCHETES
  - origem: q0
    destino: q5
    simbolos: ['[', ']']
  #OARS
  - origem: q0
    destino: q6
    simbolos: ['>']
  - origem: q6
    destino: q7
    simbolos: ['=']
  - origem: q0
    destino: q8
    simbolos: ['<']
  - origem: q8
    destino: q7
    simbolos: ['>', '=']
  - origem: q0
    destino: q7
    simbolos: ['or', 'and', 'Not']
  #IDENTIFICADOR

  #ATRIBUICAO
  - origem: q0
    destino: q9
    simbolos: ['=']
  #CONSTANTES LÓGICAS
  - origem: q0
    destino: q10
    simbolos: ['True', 'False']
  #STRING
  
